services:
  fedai:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    command: sh start.sh
    env_file:
      - .env
    volumes:
      - db_data:/app

volumes:
  db_data:
    driver: local
